apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: rain-prediction-api
  namespace: default
spec:
  endpoints:
  - interval: 10s
    port: web
  selector:
    matchLabels:
      app: rain_prediction_api
